### ISSUE TITLE
Velocity and FreeMarker

### ISSUE THREAD

**Issue by melloware** [sualeh/SchemaCrawler#103]
First of all nice job on this Library!

A couple of questions.  I have your Velocity Example working but it just outputs to the console.  

1. How do I modify the CMD file to send output to a file instead of console?

2. I notice you don't have a FreeMarker example I am assuming I can just follow the Velocity example as I see you have a FreeMarkerRenderer etc?

**Comment by melloware** [comment]
Found answer to #1 looking through your source code..

`-outputfile=tables.txt`

**Comment by melloware** [comment]
And answered #2 this works great just modified velocity.cmd to freemarker.cmd.

```
@echo off
java -classpath ../../_schemacrawler/lib/*;lib/* schemacrawler.Main -server=hsqldb -database=schemacrawler -user=sa -password= -infolevel=standard -loglevel=CONFIG -command freemarker -infolevel=maximum -sorttables=false -outputfile=tables.txt -outputformat %1
```

**Comment by melloware** [comment]
So now what I want to do is only crawl the database once but have it run on a set of Velocity or Freemarker templates.  So for example:

- audit-sql.vm
- java-pojo.vm
- java-dao.vm

Where it runs the above templates 1 for each table and generates output for a table call Foo  like...

- foo-audit.sql
- Foo.java
- FooDao.java

etc.  So I want to crawl once but have it process many templates for each table.  Is what I want possible or will it require custom coding using the API?

**Comment by sualeh** [comment]
Yes, you would have to write custom code for that.
