### ISSUE TITLE
jtds deprecated in favour of mssql-jdbc ?

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#106]
Hi @sualeh , i've discoversed that you have switcher from jtds to mssql-jdbc driver.
Can you please confirm me that so i stop jtds distribution in the deb in favour of this latest driver ?

Thank you in advance for your answer. ;-p

**Comment by sualeh** [comment]
[Adrien](@adriens), that is correct. The jTDS driver has not been updated in years. Microsoft just open-sourced it driver, and it is undergoing active development. It supports newer versions of Microsoft SQL Server. The Microsoft JDBC driver is now distributed with SchemaCrawler, instead of jTDS.

**Comment by adriens** [comment]
Great, i will package with this one ;-p
Thx for answer.
