### ISSUE TITLE
Java-API does not recognize column with unique and foreign key constraint as part of foreign key

### ISSUE THREAD

**Issue by EdgelessCube** [sualeh/SchemaCrawler#108]
So, i have a column with an unique constraint and a foreign key constraint in Oracle. In the Java-API i use: `column.isPartOfForeignKey() `
It returns false. Why is that ?

Small notice: I also created a GraphViz diagram with SchemaCrawler. There you can see the foreign key relation.

**Comment by sualeh** [comment]
Please provide more information, in the form of detailed SchemaCrawler logs. Please rerun SchemaCrawler with `-loglevel=ALL`, capture the debug logs, zip that up, and attach to this GitHub issue.

**Comment by EdgelessCube** [comment]
In my Java-Application i set log level to all with: `applyApplicationLogLevel(Level.ALL)`.

The log which was printed in the console is attached. Is that the right one, or are there other log files created when using the Java-API ? I couldn't find any other information about the logs created when using the Java-API.

For creating the log file i only retrieved the table in which the foreign key is not recognized, and i also filtered the file so you don't need to go through all `Excluding "SCHEMANAME.ATTACHMENT" since it does not match the include pattern`. 

Some more information: The table with the unique constraint and fk constraint is `USER.BULKIMPORTERROR`. The fk constraint name is `FK_BIPERR_BIPCTL_01`. It references from `USER.BULKIMPORTERROR.BULKIMPORTNUMBER` to `USER.BULKIMPORTPROCESSCRONTROL.BULKIMPOERTNUMBER`. The unique constraint name is `UX_BIPERR_BULKIMPORTNUMBER`. It's set on the column `USER.BULKIMPORTERROR.BULKIMPORTNUMBER`.

As you will see in the log file, no foreign key constraint is recognized. 

Please tell me if you need any more information.

Here is the log: 
[SchemaCrawlerBugLog.txt](https://github.com/sualeh/SchemaCrawler/files/732170/SchemaCrawlerBugLog.txt)

**Comment by sualeh** [comment]
Eric, I need some important information from the beginning of the log, which contains details of your classpath and the SchemaCraw;ler options. Can you run from the command-line, and send me that information?

**Comment by sualeh** [comment]
Eric, since it looks like you are coding your own Java application, in addition, please also send me your code, so I can take a look. In your code, please `CommandLineUtility.logSystemProperties();`, and send me the log with that information.

**Comment by EdgelessCube** [comment]
So, i've run schemacrawler from the command-line. Not sure if this log is useful, since i'm running schemacrawler from a java-application and my local installation of schemacrawler is an older version. But here it is anyway: [schemaCommandLine.txt](https://github.com/sualeh/SchemaCrawler/files/734775/schemaCommandLine.txt)

I also used `CommandLineUtility.logSystemProperties();` and ran the java-application again. Here is the log: [schemaJavaRun.txt](https://github.com/sualeh/SchemaCrawler/files/734779/schemaJavaRun.txt)

Furthermore, i've created a java class for you, which is better to look at. I was able to reproduce the error there: [schemaJavaCode.txt](https://github.com/sualeh/SchemaCrawler/files/734801/schemaJavaCode.txt) (Sorry, couldn't upload it as *.java file without zipping)

Also some additional info: This is the model of the table where i can't seem to get the foreign key (See column "BULKIMPORTNUMBER"), and the foreign key constraint in question.

![model](https://cloud.githubusercontent.com/assets/21304633/22366190/ace95756-e47b-11e6-977c-66cb08bbbc20.JPG)

![constraint](https://cloud.githubusercontent.com/assets/21304633/22366198/b2b41072-e47b-11e6-8046-53b52a93c869.JPG)

**Comment by sualeh** [comment]
You have edited out the output of `logSystemProperties()`, so I cannot tell what is going on. 

Here are some recommendations:
1. Ensure that `schemacrawler-oracle-14.10.01.jar` is on your classpath
2. Remove the following lines of code, and rerun
```
options.setTableInclusionRule(new ExcludeAll());
options.setTableInclusionRule(new RegularExpressionInclusionRule("CCP_USER.BULKIMPORTERROR"));
```

Let me know if that helps, and we can go forward from there.

**Comment by EdgelessCube** [comment]
Sorry, uploaded the wrong file. Here is the log with the logged system properties: [schemaJavaRun.txt](https://github.com/sualeh/SchemaCrawler/files/735330/schemaJavaRun.txt)
I also edited my previous comment.

> Ensure that schemacrawler-oracle-14.10.01.jar is on your classpath

 In Java i use a newer version of schemacrawler. I think the jar in in my classpath, since i use the maven repository and in the log you can see: `C:\Users\exampleUser\.m2\repository\us\fatehi\schemacrawler\14.14.01\schemacrawler-14.14.01.jar`

> Remove the following lines of code, and rerun
`options.setTableInclusionRule(new ExcludeAll());
options.setTableInclusionRule(new RegularExpressionInclusionRule("CCP_USER.BULKIMPORTERROR"));`

I only added these lines so the log would not be flooded with useless information. When removing the lines, the foreign key is still not recognized..

**Comment by sualeh** [comment]
Please include `schemacrawler-oracle-14.14.01.jar` on your classpath also, as I mentioned earlier.

**Comment by EdgelessCube** [comment]
Hello Sualeh, i've added the jar to the classpath. However, the foreign key is still not recognized. I've tried with `schemacrawler-oracle-14.14.01.jar` and `schemacrawler-oracle-14.10.01.jar`. I've also run the application with the lines removed, as you mentioned. No success.

**Comment by sualeh** [comment]
Eric, I am not able to help much with the edited logs that you have sent me. From the data that you have provided, it looks like there are no foreign keys defined in your database. Please run the following SQL statement to verify: [FOREIGN_KEYS.sql](https://github.com/sualeh/SchemaCrawler/blob/master/schemacrawler-oracle/src/main/resources/oracle.information_schema/FOREIGN_KEYS.sql).

**Comment by sualeh** [comment]
Also, please use the latest Oracle JDBC driver, since you are using Oracle JDBC driver 11.2.0.4.0 against database Oracle Database 12c Enterprise Edition Release 12.1.0.2.0, which could possibly cause issues too.

**Comment by EdgelessCube** [comment]
What data do you need exactly in the logs ? Apart from the system properties and the data related with the tables with the not-recognized foreign key ? I only removed the data not related to "BULKIMPORTERROR".

I've run your SQL statement, the foreign key `FK_BIPERR_BIPCTL_01` is found:
![image](https://cloud.githubusercontent.com/assets/21304633/22461695/91ce9102-e7aa-11e6-8edb-48aae5fec3fc.png)

Also, as i mentioned earlier, when i use schemacrawler to create a GraphViz-diagram, the foreign key is also recognized. To me it looks like the problem exists when using schemacrawler in java. 

![image](https://cloud.githubusercontent.com/assets/21304633/22462297/0459b16e-e7ad-11e6-8049-3814e28a8439.png)






Totally forgot that the database was upgraded. Thanks for the notice. However, i get the same result with the latest `ojdbc7.jar`.

**Comment by EdgelessCube** [comment]
Sualeh, i was able to reproduce the issue in a new database with only the `BULKIMPORTERROR` and `BULKIMPORTPROCESSCONTROL` table. Could you try to reproduce it ?

Simply create a new database user and execute the following sql-statements: [schemacrawler_error_testdb.txt](https://github.com/sualeh/SchemaCrawler/files/741829/schemacrawler_error_testdb.txt)

Than use schemacrawler in java and try to get the foreign key of `BULKIMPORTERROR`

![image](https://cloud.githubusercontent.com/assets/21304633/22463581/a859993c-e7b2-11e6-9e29-fc26f550d3b9.png)

**Comment by sualeh** [comment]
I will take a look.

**Comment by sualeh** [comment]
I was not able to reproduce the issue. Everything works perfectly. Please take a look at the code below. The output from the code is:

```
SCHEMACRAWLER
o--> SCHEMACRAWLER.BULKIMPORTPROCESSCONTROL
     o--> SCHEMACRAWLER.BULKIMPORTPROCESSCONTROL.KEY (NUMBER)
     o--> SCHEMACRAWLER.BULKIMPORTPROCESSCONTROL.DB_VERSION (NUMBER)
     o--> SCHEMACRAWLER.BULKIMPORTPROCESSCONTROL.BULKIMPORTNUMBER (VARCHAR2)
o--> SCHEMACRAWLER.BULKIMPORTERROR
     o--> SCHEMACRAWLER.BULKIMPORTERROR.KEY (NUMBER)
     o--> SCHEMACRAWLER.BULKIMPORTERROR.DB_VERSION (NUMBER)
     o--> SCHEMACRAWLER.BULKIMPORTERROR.BULKIMPORTNUMBER (VARCHAR2) *** part of foreign key
```

and the diagram is
![issue108](https://cloud.githubusercontent.com/assets/58572/22494348/c5ee8c30-e804-11e6-99ab-fb980f0892b7.png)

Code:
<script src="https://gist.github.com/sualeh/75c52e91bd794d01c21600b995e5fab7.js"></script>

**Comment by EdgelessCube** [comment]
Interesting... I used your code and i get a different result:

```
SCHEMACRAWLER_ERROR
o--> SCHEMACRAWLER_ERROR.BULKIMPORTERROR
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTERROR.KEY (NUMBER)
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTERROR.DB_VERSION (NUMBER)
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTERROR.BULKIMPORTNUMBER (VARCHAR2)
o--> SCHEMACRAWLER_ERROR.BULKIMPORTPROCESSCONTROL
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTPROCESSCONTROL.KEY (NUMBER)
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTPROCESSCONTROL.DB_VERSION (NUMBER)
     o--> SCHEMACRAWLER_ERROR.BULKIMPORTPROCESSCONTROL.BULKIMPORTNUMBER (VARCHAR2)
```

So the problem is my machine. Any idea what could cause the problem ?  

I'll run the code again on another machine. I'll tell you the results.

**Comment by sualeh** [comment]
Start from the basics: What operating system are you using (including version number), what version of Java, what database server version, and JDBC driver version? What version of SchemaCrawler are you using, and are you sure you have the latest version of the SchemaCrawler Oracle jar file? Are you using the same database user to create the schema as you are using to run SchemaCrawler? Are there any database permissioning issues in play?

**Comment by sualeh** [comment]
(Using a new machine is not going to guarantee that this will work. First, please make sure that you have consistent versions of everything, including database users and permissions.)
