### ISSUE TITLE
Cannot exclude columns in offline mode

### ISSUE THREAD

**Issue by ercasta** [sualeh/SchemaCrawler#109]
I have a script that generates a set of diagrams. Right now, for each diagram the script is connecting to the database, extracting the information and generating the diagram.
To speed it up, I tried to convert the script by first extracting database information once, with `-c=serialize -o=my_db.xml` and then running individual commands against the extracted database.

However, the `-excludecolumns` (specific for each diagram) don't work anymore. Is this because `-excludecolumns` is applied during database information extraction? Is there a way to apply the filter during diagram generation?

**Comment by sualeh** [comment]
Yes, `-excludecolumns` is applied during schema extraction. During diagram generation, use `-grepcolumns`.
