### ISSUE TITLE
How to generate diagram with schemacrawler-maven-plugin?

### ISSUE THREAD

**Issue by jeffjensen** [sualeh/SchemaCrawler#11]
I am struggling to find the correct configuration between pom and property files to generate a diagram.
Is it possible to do so or is the Maven plugin not able to generate the diagram?

I'm using these versions:
```
<groupId>net.sourceforge.schemacrawler</groupId>
<artifactId>schemacrawler-maven-plugin</artifactId>
<version>9.5</version>
```
```
<groupId>us.fatehi</groupId>
<artifactId>schemacrawler</artifactId>
<version>12.06.03</version>        (the latest version I found that works with Java 7)
```

**Comment by sualeh** [comment]
Jeff, unfortunately I am not maintaining the SchemaCrawler Maven Plugin too much, and it is a separate project from this one. Please check if you can execute SchemaCrawler as a Java process from your Maven project. If you can, then I would love it if you can share what you find. Otherwise, I can certainly use your help on the  SchemaCrawler Maven Plugin, if you are so inclined.

**Comment by jeffjensen** [comment]
Currently, it looks like the plugin correctly runs SchemaCrawler, but the resulting PNG is in the generated page as file contents vs an image (looks like gibberish characters).

I hope to have some time soon to try what you suggest.  Improving the plugin is ideal, but using exec may work well enough.

**Comment by sualeh** [comment]
Try using the htmlx output format. I will take a look at the plugin code when I get a chance.

**Comment by jeffjensen** [comment]
Thanks for the tip.  Your suggestion goes directly to my original question: I don't know where to specify the output format for the plugin.
  * The plugin does not have an attribute in <configuration>.
  * The plugin does not appear to see the schemacrawler.config.properties file.

**Comment by sualeh** [comment]
This issue was moved to sualeh/SchemaCrawler-Report-Maven-Plugin#1
