### ISSUE TITLE
Is it possible to get 'enum' column possible values?

### ISSUE THREAD

**Issue by artur-tamazian** [sualeh/SchemaCrawler#110]
I was trying to do it in mysql 5.6. I've got a column with type 'ENUM', but can not find its possible values.

Column definition is similar to this:
type ENUM('TYPEA', 'TYPEAB', 'TYPEC') NOT NULL;

**Comment by sualeh** [comment]
I will take a look. Meanwhile, please see if you get anything from `column.getAttribute("COLUMN_TYPE");`

**Comment by artur-tamazian** [comment]
Just tried - there's no such attribute.
Thanks for a quick reply!

**Comment by sualeh** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/sualeh/SchemaCrawler/issues/110](https://trello.com/c/lwhvOsjN/249-https-github-com-sualeh-schemacrawler-issues-110)

**Comment by sualeh** [comment]
I will take a look.

**Comment by sualeh** [comment]
[Artur](@artur-tamazian), please use the next version of SchemaCrawler, with `-infolevel=maximum`. You will get the enum values from `column.getAttribute("COLUMN_TYPE");`. If you want them as an array, you will need to parse the data that MySQL gives you in that attribute.

**Comment by artur-tamazian** [comment]
Thanks a lot! 
Do you know when will the next version be available in maven central?

**Comment by sualeh** [comment]
Please use 14.14.02 from Maven Central.

**Comment by sualeh** [comment]
You can use `schemacrawler.server.mysql.MySQLUtility.getEnumValues(Column column)` to parse MySQL enum values for a column.
