### ISSUE TITLE
SchemaCrawler - using Lint and Oracle DB

### ISSUE THREAD

**Issue by kalusalu** [sualeh/SchemaCrawler#114]
Hi, I am running a standard schemacrawler command with Lint to see the design issues that would be present in our current DB.  I am running it against Oracle 11c and it appears to have connect to the schema but I am being presented with a couple of 'Errors" when running the following:

C:\schemacrawler14\schemacrawler-14.14.03-main\_schemacrawler>schemacrawler.cmd -user=test -password=test -server=oracle -host=10.10.41.10 -database=test1 -schemas=test -c=lint -infolevel=all -outputformat=C:\output.txt -loglevel=CONFIG

The Error on screen is:

Mar 01, 2017 11:04:10 AM schemacrawler.crawl.SchemaCrawler crawlSynonyms
INFO: Not retrieving synonyms, since this was not requested
Mar 01, 2017 11:04:10 AM schemacrawler.crawl.SchemaCrawler crawlSequences
INFO: Not retrieving sequences, since this was not requested
Mar 01, 2017 11:04:10 AM schemacrawler.tools.executable.SchemaCrawlerExecutable
executeOn
INFO: Executing command "lint" using executable schemacrawler.tools.lint.executa
ble.LintExecutable
Mar 01, 2017 11:04:10 AM schemacrawler.tools.lint.LintUtility readLinterConfigs
CONFIG: Using default linter configs
Mar 01, 2017 11:04:10 AM sf.util.PropertiesUtility loadProperties
CONFIG: Cannot load properties from file <.\schemacrawler.colormap.properties>
Mar 01, 2017 11:04:10 AM schemacrawler.tools.iosource.ConsoleOutputResource open
NewOutputWriter
INFO: Opened output writer to console

[err.txt](https://github.com/sualeh/SchemaCrawler/files/811584/err.txt)

**Comment by sualeh** [comment]
Karim, please run the following command, and send me the logs as well as the output.

```
schemacrawler.cmd -server=oracle -host=10.200.18.177 -database=ASA -schemas=ASAUAT -user=asauat -password=***** -infolevel=minimum -command=list -loglevel=ALL
```

**Comment by sualeh** [comment]
This issue has been taken offline, since the submitter cannot share the logs online.
