### ISSUE TITLE
Error: Could not find or load main class schemacrawler.Main

### ISSUE THREAD

**Issue by morenoh149** [sualeh/SchemaCrawler#115]
I'm following the cross-platform installation instructions on osx

I downloaded the latest .zip from the releases page. And do
```
$ cp -R _schemacrawler/ /usr/local/bin/
$ schemacrawler.sh
Error: Could not find or load main class schemacrawler.Main
```
what did I miss?

The contents of `schemacrawler.sh` are
```
#!/bin/sh
java -cp $(echo lib/*.jar | tr ' ' ':'):config schemacrawler.Main "$@"
```

My best guess is I need to place the necessary .jar files somewhere. Where should I place `schemacrawler-14.14.03.jar` and `schemacrawler-postgresql-14.14.03.jar`?

**Comment by sualeh** [comment]
Please take a look at a solution from @David-Guillot - https://gist.github.com/David-Guillot/dd53227141fd62ff5db6ef23c929f7b1

**Comment by morenoh149** [comment]
@sualeh what is the root of the motivation to not make this the default? the instructions suggest as long as schemacrawler is in the path it should work fine. What is the "correct" location to place schemacrawler?

**Comment by morenoh149** [comment]
Using the .sh file in the gist returns
```
$ schemacrawler.sh
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
Error: Could not find or load main class schemacrawler.Main
```

**Comment by sualeh** [comment]
Try this:
```
DIR=/usr/local/bin/
java -cp $(echo $DIR/lib/*.jar | tr ' ' ':'):config schemacrawler.Main "$@"
```

**Comment by morenoh149** [comment]
that works :)

**Comment by sualeh** [comment]
Great!

**Comment by sualeh** [comment]
@morenoh149 - The root motivation not to make this a default is that there there is no real installer for SchemaCrawler, other than unzipping a zip file. I do not want to write an installer at this point. If there is no installer, people are free to move the SchemaCrawler folder to any location. At that point, they are responsible for writing their own commands, based on @David-Guillot GitHub Gist.

**Comment by LednevaAR** [comment]
Hello. I get the error: Error: Could not find or load main class schemacrawler.Main
Caused by: java.lang.ClassNotFoundException: schemacrawler.Main
Changing file contents schemacrawler.sh doesn't help. Help me, please, how can I fix this error?

**Comment by sualeh** [comment]
@LednevaAR - I am not able to support you in this. SchemaCrawler is distributed as a zip file with jar files, and you are free to write your own script if the one that is provided does not work for you.

**Comment by sualeh** [comment]
@LednevaAR - please use [another distribution for SchemaCrawler](https://www.schemacrawler.com/downloads.html). There are many options.
