### ISSUE TITLE
Fixing licensing for hsqldb, postgresql, and sqlserver modules

### ISSUE THREAD

**Issue by shantstepanian** [sualeh/SchemaCrawler#118]
Followup from issue #117 - I saw the licenses fixed for schemacrawler, db2, Oracle, and Sybase IQ

However, I still see hsqldb, postgresql, and sqlserver as GPL. The underlying drivers are BSD, BSD, and MIT license, respectively. Is it possible to change those as well? I'm not aware of the license compatibilities, though BSD and MIT are permissive

(We aren't yet using other distributions not named above, so I can't comment yet on whether the others are correct, but I can deal without the others for now)

**Comment by sualeh** [comment]
[Shant](shantstepanian), I have clarified the
[licensing](http://sualeh.github.io/SchemaCrawler/license.html) terms. I will release a new version of SchemaCrawler with the jar files updated with the latest POMs.

**Comment by shantstepanian** [comment]
Thanks! Confirming that the licensing looks fine now
