### ISSUE TITLE
Is possible to connect with Teiid JDV?

### ISSUE THREAD

**Issue by luizsoliveira** [sualeh/SchemaCrawler#12]
Dear,

I do not know if this is the ideal channel to ask that question, but I thank you for understanding.

I have used the schema crawler to discover Postgres and MySQL databases structures.

I am interested in doing the same job with the Teiid (http://teiid.jboss.org/) through the specific connector JDBC.

I wonder if anyone has ever done that? And what steps should be taken?

On the next page (http://sualeh.github.io/SchemaCrawler/plugins.html) it was not clear if'll have customizes the generated code with the specificities of Teiid. At the moment I do not have intimate knowledge of how the Teiid works.

**Comment by sualeh** [comment]
SchemaCrawler can connect to any database system that provides a JDBC driver. I have not specifically tested with Teiid, but theoretically, it should work out of the box. There is no code generation needed, and no additional code that you need to write. You will have to make sure that you use the `-url` command-line argument, and not the `-server`, `-host`, and `-port` arguments.

**Comment by luizsoliveira** [comment]
Thanks for the quick response.

Yes , I get it , I will use the url parameter instead of others, but how
can I do for crawler schema using the JDBC driver Teiid ?

Tranks

Good rest
Em 08/10/2015 18:25, "Sualeh Fatehi" <notifications@github.com> escreveu:

**Comment by sualeh** [comment]
Here is how you get the URL: https://goo.gl/GUKISv

**Comment by luizsoliveira** [comment]
Thank you!

The connection worked with the following parameters:

-Djavax.net.ssl.trustStore=PATH-TO-TRUSTSTORE-PRO.jks \
-cp $(echo lib/*.jar | tr ' ' ':') schemacrawler.Main \
-command=schema \
-url=jdbc:teiid:DATABASE_NAME@mms://HOST:31000 \
-u=USER \
-password=PASSWORD \
-infolevel=detailed \
-outputformat=json \
-loglevel=CONFIG \
-outputfile=PATH/schema.json

The following file is included in:
schemacrawler-14.03.03-main/_schemacrawler/lib/teiid-8.4.3-redhat-1-jdbc.jar

**Comment by luizsoliveira** [comment]
But still can not generate the full schema because the process is paralyzed in the step of obtaining weak associations.

Changing the infolevel to minimum, standard or detailed did not return information about the columns of the tables. For instance:

{
      "foreignKeys": [],
      "indexes": [],
      "columns": [],
      "name": "XX_XX_XX_XXXXXX_XXXXXX",
      "fullName": "XX_XX_XX_XXXXXX_XXXXXX",
      "type": "table",
      "triggers": [],
      "tableConstraints": [],
      "remarks": "Rotated MUPE Table",
      "primaryKey": {
        "unique": true,
        "name": "XX_XX_XX_XXXXXX_XXXXXX"
      }
    },

For all 281 tables of the model, the schemacrawler return an empty set of columns.

**Comment by sualeh** [comment]
Please use `-infolevel=standard` for now, and turn on logging with `-loglevel=CONFIG`. Then, send me the log file at sualeh@hotmail.com
