### ISSUE TITLE
is there any way to check if a view is a materialized view

### ISSUE THREAD

**Issue by starbassma** [sualeh/SchemaCrawler#122]
Hello, i would like to thank you for this library,
i want to know if is there any way to check for materialized views

**Comment by sualeh** [comment]
I would need more information to answer that question. Please look at [Guidelines for Support](http://sualeh.github.io/SchemaCrawler/consulting.html) for details on what information is needed.

**Comment by starbassma** [comment]
Thanks for the prompt answer,
When i query the schema object to get the database views it doesn't include materialized views, instead they appear as instance of Table class, it's a bit confusing since we can't distinguish between real tables and materialized views because they are all recognized as instances of Table .
@sualeh 
Nb: i'm querying an Oracle 11g2 database.

**Comment by sualeh** [comment]
You should be able to use a [Data Dictionary View](http://sualeh.github.io/SchemaCrawler/data-dictionary-extensions.html), with a query to `ALL_MVIEWS`.

**Comment by starbassma** [comment]
@sualeh 
Thanks,
Is there any way to configure it pragmatically without editing the configuration file (schemacrawler.config.properties) since i use the api (jar file)

**Comment by sualeh** [comment]
You can do this in code. You will need to use a DatabaseSpecificOverrideOptionsBuilder and an InformationSchemaViewsBuilder to create DatabaseSpecificOverrideOptions. It may be easier to write a custom version of the [SchemaCrawler - Oracle plug-in](https://github.com/sualeh/SchemaCrawler/tree/master/schemacrawler-oracle), though.

**Comment by starbassma** [comment]
thank  you
