### ISSUE TITLE
output Lints as csv

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#128]
hi Sualeh, is there any proper way to export lint report as csv ? I'd like to play with lint reports from python/R to perform some stats on them ;-p

**Comment by sualeh** [comment]
I will try to give you some sample code.

**Comment by adriens** [comment]
Great, thanks @sualeh  !

**Comment by adriens** [comment]
Should it be developed as a plugin ?

**Comment by sualeh** [comment]
Yes. Please go ahead and develop a plugin that meets your needs.

**Comment by adriens** [comment]
OK @sualeh , thanks for your answer, i was not impatient but just wanted to be sure to develop thie feature at the right place ;-p

**Comment by adriens** [comment]
I guess you can now close this issue ;-p

**Comment by sualeh** [comment]
Well, I have a better idea. You can try this Gist out! https://gist.github.com/sualeh/8cd3df1d4add9b9391875cc7c79ca6c0

**Comment by sualeh** [comment]
@adriens - please let me know how the scripting solution works for you.

**Comment by adriens** [comment]
Also done with csv plugin see https://github.com/adriens/schemacrawler-csv-plugin

**Comment by sualeh** [comment]
👍 My favorite line is [the one that gives you mints](https://github.com/adriens/schemacrawler-csv-plugin/blob/master/src/main/java/com/github/adriens/AdditionalCommandProvider.java#L15)!

**Comment by adriens** [comment]
Fixed, ths @sualeh

**Comment by sualeh** [comment]
I liked it better when you got mints! I like mints. ;-)

**Comment by adriens** [comment]
For sure, tastes much better !
