### ISSUE TITLE
Command hangs and nothing happends

### ISSUE THREAD

**Issue by hryamzik** [sualeh/SchemaCrawler#129]
```
./schemacrawler.sh -server=sqlserver -user=sa -password=password -host=db -port=1441 -database=mydb -c schema -infolevel=maximum -tabletypes=TABLE -outputformat=pdf -outputfile=database-diagram.pdf
```

This command just never ends with no output. How can I debug this?

P.S.: however pdf was generated an hour later.

**Comment by sualeh** [comment]
Does the command return without the
'-outputformat=pdf -outputfile=database-diagram.pdf'
options?

**Comment by hryamzik** [comment]
Started, I'll let you know. Also tried to generate dot file and looks like command returns only some time after I break connection.

**Comment by sualeh** [comment]
Please first try without the `-outputformat=pdf -outputfile=database-diagram.pdf` options. If that works, you can try with `-outputformat=scdot`.  (**Note:** Not `dot`.)

**Comment by hryamzik** [comment]
Tried without output options, same behaviour. Closing connection (VPN disconnect) helps.

**Comment by sualeh** [comment]
You will need to generate debugging information. Please use an additional command-line argument of `-loglevel=ALL`, and send me the logs. Please follow instructions in [Guidelines for Support](http://sualeh.github.io/SchemaCrawler/consulting.html).

**Comment by sualeh** [comment]
Roman, @hryamzik - I am still waiting for your logs.

**Comment by hryamzik** [comment]
Tried twice, once with no otput and then with PDF generation, both time succeed in 1.5 hours. Not sure if logging affects behaviour but I can't reproduce hanging with them. Thanks!
