### ISSUE TITLE
Derby jdbc driver disappeared from the distribution ?

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#13]
It seems like Derby jdbc driver has been removed from schemacrawler distribution.

**Comment by adriens** [comment]
I also see that there is no schemacrawler-derby 14.04.03 in public repos. It really seems like the derby support is off now.

**Comment by adriens** [comment]
should i still leave the driver in the debian package ?

**Comment by adriens** [comment]
these questions are for the debian package of the ```14.04.03``` ;-p

**Comment by adriens** [comment]
i'm waiting for your feedback to upload this latest package to bintray.

**Comment by sualeh** [comment]
You can leave the driver in. SchemaCrawler still supports Apache Derby, but without extended functionality.

**Comment by adriens** [comment]
That's what i was guessing. I leave the driver so people can use the jdbc url path ;-p

**Comment by adriens** [comment]
New debian package released.

**Comment by sualeh** [comment]
Thanks, Adrien
