### ISSUE TITLE
performance issues with file output

### ISSUE THREAD

**Issue by cemeyer2** [sualeh/SchemaCrawler#130]
when running on a database schema with 50k tables, the strategy for writing to file is inefficient and causes performance issues. On a particular run, the output from schemacrawler was a single 6.2 gigabyte html file and required over 25 gigabytes of heap in the JVM. Looking at the code, it appears that the entire charsequence is being stored in memory before being serialized out to disk rather than being written as it is generated.

To close this issue as fixed, the acceptance criteria might be that output is not completely buffered in memory before being flushed to disk.

**Comment by cemeyer2** [comment]
label here should be `bug`

**Comment by sualeh** [comment]
Charlie @cemeyer2, SchemaCrawler holds the entire catalog in memory, and in your case it is big. However, when the file is generated, it is streamed, as far as I can tell. If your analysis shows that in addition to the catalog in memory, the file contents are held in memory too, please point me to that location in code, so I can take a look. Thanks.

**Comment by sualeh** [comment]
Charlie @cemeyer2, please follow the guidelines on [SchemaCrawler Support and Consulting](http://sualeh.github.io/SchemaCrawler/consulting.html). Thanks.
