### ISSUE TITLE
Plugin New SchemaCrawler Commands > archetype issue

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#131]
Actually, the generation does not generate an out of the compilable project :

![schemacrawler_archetype](https://user-images.githubusercontent.com/5235127/28294599-dc4b4e2a-6ba6-11e7-8e87-d8c32205e4c8.png)

In the archetype, on , could you please add the following code to ```AdditionalCommandProvider.java``` :

```java
@Override
  public String getHelpAdditionalText(){
      return "Additional Help text";
  }
```

**Comment by adriens** [comment]
The archetype used was :

```
-DarchetypeGroupId=us.fatehi -DarchetypeArtifactId=schemacrawler-archetype-plugin-command -DinteractiveMode=false
```

**Comment by sualeh** [comment]
Do you need a new SchemaCrawler release right now, or can it wait for the next release?

**Comment by adriens** [comment]
We can wait for the next release, of course !...it really is a very minor issue :smile_cat:
