### ISSUE TITLE
Reason for AUTHID clause in Oracle ROUTINES.sql file

### ISSUE THREAD

**Issue by shantstepanian** [sualeh/SchemaCrawler#137]
Hi, when using SchemaCrawler for Oracle, I found that I wasn't getting back data for routines that I had requested.

The routines were created as a DBO id (i.e. a DBO id created by Amazon RDS for an Oracle instance based in Amazon)

Upon debugging, it was because of this clause:
    PROCEDURES.AUTHID = 'CURRENT_USER'

AUTHID is described as follows: https://docs.oracle.com/cd/E11882_01/server.112/e40402/statviews_2013.htm#REFRN20168

Do you recall why we needed that AUTHID clause? I would need to remove it in my own code for it to work; otherwise, the query is fine for me. But I don't know the impact this would have on others

**Comment by sualeh** [comment]
I do not see a good reason for this. I will remove it.

**Comment by shantstepanian** [comment]
Thanks! Regarding a release - I'm still trying out a couple things, so no rush on my end at this time

**Comment by sualeh** [comment]
I will get the release out on the weekend

**Comment by sualeh** [comment]
Released
