### ISSUE TITLE
Create diagram with tables and relationships

### ISSUE THREAD

**Issue by sualeh** [sualeh/SchemaCrawler#141]
Create diagram with just tables and relationships, not displaying any columns.

(Idea from @jbr)

**Comment by adriens** [comment]
This kind of think is often provided by sql clients, like OmniDB :

https://github.com/OmniDB/OmniDB

See the section :

> Graphs displaying tables and their relations


![omnidb](https://user-images.githubusercontent.com/5235127/31974879-97ffe48a-b979-11e7-9532-b6d656f445da.png)

**Comment by sualeh** [comment]
Thanks, @adriens I will see if I can find some time to implement this. I am not sure how useful this kind of diagram would be. If someone needs something like this, a [schemaball](http://mkweb.bcgsc.ca/schemaball/?screenshots) is more fun!

**Comment by adriens** [comment]
@sualeh  it was to to say that it should be implemented but rather to give an easy way of doing this without having to dev.

shemaball is in fact a graph : i'm pretty sure we could do this with the dot version...and even more with more dedicated graph formats... in fact, theses days we add to generate huge database schemas that were hard to fit in a pdf...and even harder to open the pdf as it was really huge.

Just a few minutes ago i tried to produce a dot file as db schema and then display it in gephi, the dot file was not looking good : can you please confirm me the command line to user to do so ?

My conviction is that schemacrawler is a great producer of graph data...but that the drawing task should be (as it is the case with graphviz) delegated to dedicated tools like Gephi, Tuleap, yEd...and this can be done thanks to portable graph formats....hence the schemaball could be produced just as any other layout... don't you think so ? If so, from my opinion, schemacrawler could keep on focusing on its job..but get a huge set of new drawing possibilities.

I'll rework on the Neo4j approach as peforming graph oriented queries on database model is pretty convenient too...but as i do this on spare time, it's not easy to save enough time, you know : i have too much ideas and not enough time to implement them.

So...after my long comment : what's your opinion on this approach ?...whic also leads to generative and data art ? <3

**Comment by adriens** [comment]
In fact, at a given level, form i cold experience until now, it's like you add to make a choice between :

- Getting  a nice displayable graph
- Getting a strcuture on which you can query metadatas, relations, groups, aggregations, detect clusters, compute histograms, detect patterns, etc...

**Comment by adriens** [comment]
Just to know : from your point of view, would you rather focus :

1. - on being able to draw in an aesthetic way larges schema graphs
2. - generate structure you can query

I guess the second option is slightly  more interesting 'cause you can report on it but also (with some additional work) draw it...still the 1st option should be more esthetic and eay to use for end user

What's your opinion ?

**Comment by sualeh** [comment]
I think #2 also.

**Comment by sualeh** [comment]
That is why I think your neo4j is a good idea, and sufficient.

**Comment by adriens** [comment]
Yes, so i have to rework on it ;-p and use bolt instead of write on server side files. It should be easier to use at the end.
From R you can draw some fun things by connecting on neo4J (see https://www.linkedin.com/pulse/non-le-basilic-nest-pas-au-centre-de-la-cuisine-ni%C3%A7oise-adrien-sales/)

**Comment by adriens** [comment]
Fixed in https://github.com/adriens/schemacrawler-plugin-neo4j/issues/10
