### ISSUE TITLE
Versioning schema of the schemacrawler artifact is not following Maven rules

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#145]
Hi,

to keep up-to date from my projects that depend on schemacrawler i do now user Gemnasium. But due to the -java7 suffix on schemacrawler, it seems like the versioning schema of that artifact is not following Maven rules:

https://maven.apache.org/pom.html#Version_Order_Specification

As you can see, on Maven central the latest version for that artifact is 14.16.04-java7 too: 
http://search.maven.org/#search%7Cga%7C1%7Ca%3A%22schemacrawler%22

What could be done to better follow these requirements ?

**Comment by sualeh** [comment]
Unfortunately, nothing. Maven has buggy and incomplete support for classifiers. The only way to distinguish between classifiers is to include the classifier as part of the version number. Initially, I tried using a classifier of "java7", but then I could not build javadocs and sources, which are required to upload to the Central Repository.

**Comment by adriens** [comment]
Damned ;-p

Thanks @sualeh
