### ISSUE TITLE
[enhancement] Get database object unquoted name

### ISSUE THREAD

**Issue by ewanld** [sualeh/SchemaCrawler#146]
Hi!

I would like to retrieve only unquoted names for database objects. As far as I understand, names are quoted when they clash with a SQL reserved word but the behavior is not configurable.

To work around the issue I unquote them manually. For instance:
```java
final Identifiers identifiers = Identifiers.identifiers().withConnection(connection).build();
identifiers.unqotedName(column.getName());
```

Would you consider adding an option in SchemaCrawlerOptions to make the behavior configurable (for instance an enum QUOTE_ALWAYS/QUOTE_SOMETIMES/QUOTE_NEVER) ? Or having a new method getNameUnquoted() ?

Thank you for your time!

**Comment by adriens** [comment]
You mean a littl ebit like the objectQuotingStrategy on Liquibase ?

**Comment by ewanld** [comment]
Yes the idea is similar to ObjectQuotingStrategy from liquibase

**Comment by sualeh** [comment]
Good idea. I will see how I can do this.
