### ISSUE TITLE
Make the typeMap used by RetrievalConnection customizable

### ISSUE THREAD

**Issue by yamass** [sualeh/SchemaCrawler#153]
# Context
[RedG](https://github.com/btc-ag/redg) uses SchemaCrawler to extract information about the corresponding Java data types for columns. (and for many other things, too - thanks, by the way!!)

# Problem 
H2 returns `null` for `Connection.getTypeMap()`. Therefore, `RetrievalConnection.typeMap` falls back to `schemacrawler.utility.TypeMap#createDefaultTypeMap()`. 

However, we need to get the Java type for `TIMESTAMP WITH TIME ZONE`, which is not contained in the default map.

# Suggested Solutions
### Solution 1 (preferred)
Make the `typeMap` used by `RetrievalConnection` customizable in the same way as many other properties of `RetrieverConnection`, using `DatabaseSpecificOverrideOptions`.

### Solution 2
Add `TIMESTAMP WITH TIME ZONE` to the `schemacrawler.utility.TypeMap#createDefaultTypeMap()`.

We will work-around this issue as long as it is not fixed. So no hurry.

**Comment by yamass** [comment]
Excellent! Thank you.

**Comment by sualeh** [comment]
You're welcome. Please use SchemaCrawler 14.17.04.

**Comment by sualeh** [comment]
The next version of SchemaCrawler will have support for TIMESTAMP_WITH_TIMEZONE and TIME_WITH_TIMEZONE.

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.21.02
