### ISSUE TITLE
How to get oracle stored procedure

### ISSUE THREAD

**Issue by BloodNoteII** [sualeh/SchemaCrawler#159]
# Environment

 SchemaInfoLevel level = SchemaInfoLevelBuilder.detailed();
		options.setSchemaInfoLevel(level);
		options.setRoutineInclusionRule(new IncludeAll());
		options.setColumnInclusionRule(new IncludeAll());
	        options.setTableInclusionRule(new IncludeAll());
		options.setSequenceInclusionRule(new IncludeAll());
  for (final Schema schema: catalog.getSchemas()){
		 for (final Routine routine : catalog.getRoutines(schema)) {
}

# Issue

2018 4:55:10 下午 schemacrawler.crawl.RoutineRetriever retrieveProcedures
Cannot locate schema, so not retrieving procedures for schema: 
一月 29, 2018 4:55:10 下午 schemacrawler.crawl.RoutineRetriever retrieveFunctions
Cannot locate schema, so not retrieving functions for schema: 

cannot get any routines, Is there an example of getting a Oracle stored procedure

**Comment by sualeh** [comment]
Please run SchemaCrawler from the commnd-line, obtain logs using `-loglevel=ALL` and attach the logs to this issue.
