### ISSUE TITLE
Retreiving Sequences on PostGres 9.4 doesn't seems to work

### ISSUE THREAD

**Issue by sardineuser** [sualeh/SchemaCrawler#16]
Hello,
retreiving sequences included in schemas return empty list with Java API on PostGres.
infoLevel is set to maximum.

 for (final Sequence sequence : catalog.getSequences(schema)) {
...}

**Comment by sualeh** [comment]
Please set a sequence inclusion rule, using
`schemacrawler.schemacrawler.SchemaCrawlerOptions.setSequenceInclusionRule(InclusionRule)`

**Comment by sardineuser** [comment]
Great ! it's ok. Thanks a lot Sualeh.
