### ISSUE TITLE
How to get column and table information by SQL script

### ISSUE THREAD

**Issue by jewway** [sualeh/SchemaCrawler#160]
# Environment
SchemaCrawler version: 14.16.04
Java version:  8
OS : Wwindows
Database: MS SQL
JDBC Driver : sqljdbc42

# Issue
I use `SchemaCrawlerUtility.getResultColumns(rs)` to retrieve all column information but i can't use `column.getParent()` to get any table information by column.

![image](https://user-images.githubusercontent.com/3501899/35667831-0118af90-076a-11e8-8b87-bf5412ebe32d.png)

**Comment by sualeh** [comment]
What happens? Do you get an exception? What is the SELECT statement for your ResultSet?

**Comment by sualeh** [comment]
@jewway Unfortunately, the JDBC driver does not return the table data. Please file a bug/ enhancement request with Microsoft, at [mssql-jdbc](https://github.com/Microsoft/mssql-jdbc).
