### ISSUE TITLE
TABLE_COLUMNS.sql not working for Oracle 11g

### ISSUE THREAD

**Issue by uppalabharath** [sualeh/SchemaCrawler#162]
# Environment

> Windows
> schemacrawler-14.19.01-distribution
> Database: Oracle 11g
> Driver: ojdbc6

# Issue

The table_columns.sql query is added with a new column named IDENTITY_COLUMN that is specific to Oracle 12c DB. As the column is missing in older versions of Oracle DB, the query fails with an ora 00904 invalid identifier error. 

My 2 cents:  Try to hit the 12c Query first if it fails, fallback to the older query where 'NO' as is_autoincrement is used in place of IDENTITY_COLUMN as is_autoincrement

**Comment by sualeh** [comment]
Thanks . Oracle 11g has ended its support lifetime. Oracle 12c was introduced in 2013. SchemaCrawler will not support Oracle 11g. I understand that your organization may still be using Oracle 11g, though. 
You may need to write your own plugin for SchemaCrawler, or see if you can use DatabaseSpecificOverrideOptionsBuilder to change the table column retrieval strategy.

**Comment by cwichoski** [comment]
This was removed from newer versions?

**Comment by sualeh** [comment]
@cwichoski The policy is for SchemaCrawler database plugins to support only the database versions supported on AWS. You can run SchemaCrawler without the SchemaCrawler Oracle database plugin, which will provide basic functionality with Oracle 11g. Otherwise, you can [request support](https://www.schemacrawler.com/consulting.html).

**Comment by cwichoski** [comment]
@sualeh, thank you, without oracle plugin it worked, for now I'm using schemacrawler to study old database structures

**Comment by sualeh** [comment]
@cwichoski Good to hear that it worked for you.
