### ISSUE TITLE
Connecting to SQL Server

### ISSUE THREAD

**Issue by suntong** [sualeh/SchemaCrawler#164]
From https://github.com/sualeh/SchemaCrawler/issues/90

> Please use the URL version of SchemaCrawler command-line, and follow the instructions to construct a URL in jTDS FAQs

So I did it, 

```
> java -classpath ../../_schemacrawler/lib/*;lib/* schemacrawler.Main -url="jdbc:jtds:sqlserver://Db04:1433/Test2010;user=sa;password=s3cr3t" -infolevel=standard -command=schema -outputformat=dig -outputfile=database-diagram.dig -loglevel=CONFIG %*
Picked up _JAVA_OPTIONS: -Xmx512M
SchemaCrawler 14.19.01
Database schema discovery and comprehension tool
Copyright (c) 2000-2018, Sualeh Fatehi <sualeh@hotmail.com>.

You can search for database schema objects ... SchemaCrawler also generates schema diagrams.
password:
Feb 14, 2018 6:04:14 PM sf.util.PropertiesUtility loadProperties
CONFIG: Cannot load properties from resource <null>
Feb 14, 2018 6:04:14 PM schemacrawler.schemacrawler.BaseDatabaseConnectionOptions getConnection
WARNING: Database user is not provided
SchemaCrawler 14.19.01

Error: Could not find a suitable JDBC driver for database connection URL, jdbc:jtds:sqlserver://Db04:1433/Test2010;

Or, re-run SchemaCrawler with an additional
-loglevel=CONFIG
option for details on the error
Feb 14, 2018 6:04:14 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: SchemaCrawler, v14.19.01
Feb 14, 2018 6:04:14 PM us.fatehi.commandlineparser.CommandLineUtility logSafeArguments
INFO: Command line:
-url=jdbc:jtds:sqlserver://Db04:1433/Test2010;user=sa;password=s3cr3t
-infolevel=standard
-command=schema
-outputformat=dig
-outputfile=database-diagram.dig
-loglevel=CONFIG
%*
Feb 14, 2018 6:04:14 PM us.fatehi.commandlineparser.CommandLineUtility logFullStackTrace
SEVERE: Could not find a suitable JDBC driver for database connection URL, jdbc:jtds:sqlserver://Db04:1433/Test2010;user=sa;password=s3cr3t
schemacrawler.schemacrawler.SchemaCrawlerSQLException: Could not find a suitable JDBC driver for database connection URL, jdbc:jtds:sqlserver://Db04:1433/Test2010;user=sa;password=s3cr3t
        at schemacrawler.schemacrawler.BaseDatabaseConnectionOptions.getJdbcDriver(BaseDatabaseConnectionOptions.java:369)
 
```

Anything wrong with my jTDS URL? 
Can you give me a working jTDS URL sample please? 
Thx!

**Comment by suntong** [comment]
I tried to add `domain=[DomainName];` to above url and it is still not working either. 

BTW, It is not the password problem, I've double-checked it. 

From this, 

`WARNING: Database user is not provided`

it seems that the whole `domain=[DomainName];user=[username];password=[password]` was not correctly passed to whatever is anticipating it.

**Comment by sualeh** [comment]
SchemaCrawler is not distributed with the jTDS JDBC driver any more - please see the following message in your log:
`Error: Could not find a suitable JDBC driver`

SchemaCrawler comes bundled with the [Microsoft JDBC Driver for SQL Server](https://github.com/Microsoft/mssql-jdbc). Please contact Microsoft for support with this JDBC driver.

**Comment by suntong** [comment]
k. thx. 

well, the only reason I look into the old issue archive is that the suggested method in doc didn't work for me. here are the details:

```
INFO: Making connection to jdbc:sqlserver://localhost:1433;databaseName=Test2010;applicationName=SchemaCrawler
for user 'sa', with properties {}
SchemaCrawler 14.19.01

Error: Could not connect to jdbc:sqlserver://localhost:1433;databaseName=Test2010;applicationName=SchemaCrawler, for user 'sa', with properties {}
```

Maybe the http://www.schemacrawler.com/database-support.html, at least the 
`-server=sqlserver -host=localhost -port=1433 -database=schemacrawler -schemas=schemacrawler.dbo -user=schemacrawler -password=schemacrawler` part, should be corrected.
