### ISSUE TITLE
Schema crawling

### ISSUE THREAD

**Issue by koxa29** [sualeh/SchemaCrawler#19]
Hello, Sualeh

As I understood first schema crawler searches catalog by regexps and then schema should be retrieved by calling Catalog.lookupSchema. I use includeFilter "^`?" + table_name + "`?$" since table_name could be with or without apostrophe. For example, if I try to crawl DB with name "new", I retrieve catalog "`new`", but lookupSchema returns empty optional. Is it possible to use lookupSchema with regexp?

Thank you.

**Comment by sualeh** [comment]
Denys, I will add in a feature to look up database objects by a regular expression.

**Comment by koxa29** [comment]
Thank you very much)

**Comment by sualeh** [comment]
I will close this issue when I release the enhancement.

**Comment by sualeh** [comment]
I have put something in place for you to do this - please take a look at
https://goo.gl/vGQa0J and let me know.

On Mon, Dec 14, 2015 at 4:41 AM, Denys Konakhevych <notifications@github.com

**Comment by sualeh** [comment]
Added a utility to filter database objects in 14.05.05.
