### ISSUE TITLE
Add jxr to maven site report

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#2]
Add jxr (https://maven.apache.org/jxr/maven-jxr-plugin/examples/linkjavadoc.html) to maven site so people can easily browse javadoc up to real java code.

**Comment by sualeh** [comment]
Adrien, I had used JXR in the past, but I think it has limited value. Most modern IDEs such as Eclipse allow you to link the source jar file to your binary jar file. They also show you javadocs, and code. This is more interactive while developing, rather than referring to a webpage.
