### ISSUE TITLE
SqlServer connection pattert

### ISSUE THREAD

**Issue by koxa29** [sualeh/SchemaCrawler#20]
Hello, Sualeh

I try to inspect MySQL database using connection like "jdbc:sqlserver:". However, SchemaCrawler resolves SqlServerDatabaseConnector if connection starts with "jdbc:jtds:sqlserver:". Is it possible to change connectionUrlPattern from "jdbc:jtds:sqlserver:.*" to "jdbc:(jtds:)?sqlserver:.*" ?.

Thank you

**Comment by sualeh** [comment]
Please let me know exactly which database and which JDBC driver you wish to use. There seems to be some inconsistency here. By default, SchemaCrawler supports the open source jTDS driver for Microsoft SQL Server.

**Comment by koxa29** [comment]
Hello, Sualeh

We tried jTDS and it works fine. Thank you for your reply. Issue is not valid.
