### ISSUE TITLE
Release binaries straight to gh from travis

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#24]
Hi Sualeh,

i've just tested this : https://docs.travis-ci.com/user/deployment/releases
on the debian installer of schemacrawler. It is just great !
You push a tag, and from travis, you upload any produced file to the github release. I'm pretty sure that if you take a look at it you will :heart: it !
Have a nice week end.

Personally, i will remove bintray uploads and let travis and github do the whole stuff for now : the release process is much lighter like that.

**Comment by sualeh** [comment]
The SchemaCrawler release process is a little more complex.

**Comment by adriens** [comment]
don't you generate the zip file on any directory ? How could i help ?

**Comment by sualeh** [comment]
Done. See release 14.07.02. Thanks for pushing me!

**Comment by adriens** [comment]
You did it !!!
:+1: :+1: :+1: :+1: :+1: 

You will se that you will release for often and earlier now... i did notice that on my projects.
