### ISSUE TITLE
Add https://www.versioneye.com badge

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#26]
.... to monitor dependencies level at no cost

**Comment by adriens** [comment]
you can get a quick look at outdated deps at : https://www.versioneye.com/user/projects/56b687660a0ff5002c860389

as i have activated it in the debian packager

**Comment by sualeh** [comment]
VersionEye does not support Maven modules. I have been talking to the developers since over a year, and they have not fixed it yet.

**Comment by adriens** [comment]
Hmmm, very bad point for them... this is very disappointing ;-(

**Comment by adriens** [comment]
@sualeh : take a look at this : https://bitbucket.org/versioneye/versioneye/issues/92/maven-multimodules-handling

maybe these are good news !!!

**Comment by adriens** [comment]
> But the VersionEye Maven Plugin works perfectly on any CI System ;-) 

... travis should be able to do it hence ! :+1:
