### ISSUE TITLE
Dependencies update

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#29]
- xpp3_min : shall we switch to 1.1.3.4.O ... ?...or will we always stay on this version ?
- xstream : **our version seems pretty out of date**, see https://www.versioneye.com/java/com.thoughtworks.xstream:xstream/1.4.7 : shall we upgrade to 1.4.8  ?
- sqlite-jdbc : does the 3.8.11.2  fix the bug sc does encounter ?

I'm asking this so i can flag some of them as non upgradable in the dependencies, see https://www.versioneye.com/user/projects/56b687660a0ff5002c860389

Thank you in advance for your answser.

**Comment by sualeh** [comment]
sqlite-jdbc is a non-upgradeable dependency. They have not fixed the issue.

**Comment by adriens** [comment]
ok, so i mark it as non upgradable.
Thx. Btw, what is the exact bug on this driver ?

**Comment by adriens** [comment]
i have muted the versioneye on that.

What about xpp3_min and xstream please ?

**Comment by sualeh** [comment]
SchemaCrawler already uses XStream 1.4.8

**Comment by adriens** [comment]
not in the zip file you release, see https://github.com/sualeh/SchemaCrawler/issues/28

**Comment by adriens** [comment]
so, it will only remain `xpp3_min` to  `1.1.3.4.O`  ?

**Comment by sualeh** [comment]
No, trying to track it down - XStream uses xpp3_min 1.4c.

**Comment by sualeh** [comment]
Committed. Will be fixed in the next version.
