### ISSUE TITLE
How to hide SchemaCrawlerHeaderInfo in the output

### ISSUE THREAD

**Issue by hongjn** [sualeh/SchemaCrawler#33]
How to hide SchemaCrawlerHeaderInfo in the output ?

**Comment by sualeh** [comment]
Are you using the command-line or the API?

**Comment by hongjn** [comment]
command-line, my output format is JSON.

**Comment by sualeh** [comment]
Use `-noinfo`

**Comment by hongjn** [comment]
Very thanks.
