### ISSUE TITLE
Get a nice (and beautiful) svg version of schemacrawler logo

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#42]
... so we can embed it easier in html5 prezz ;-p... or print T-Shirts LOL

**Comment by sualeh** [comment]
https://github.com/sualeh/SchemaCrawler/blob/master/schemacrawler-docs/schemacrawler_logo.svg

**Comment by adriens** [comment]
looks strange on gh viewer ;-(

**Comment by adriens** [comment]
It looks strange :

![2016-03-17 18_11_16-schemacrawler_schemacrawler_logo svg at master sualeh_schemacrawler](https://cloud.githubusercontent.com/assets/5235127/13838944/c49d658a-ec6b-11e5-9d82-db17d3af2110.png)

**Comment by sualeh** [comment]
Sorry! It is fixed now.

**Comment by adriens** [comment]
Yep, it's great now. Thx @sualeh
