### ISSUE TITLE
Implement console code completion on oh-my-zsh

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#44]
![tty](https://cloud.githubusercontent.com/assets/5235127/13907844/568259ce-ef4b-11e5-8110-18800047053d.gif)

**Comment by adriens** [comment]
I'm working on it, cf https://github.com/robbyrussell/oh-my-zsh/pull/4934

**Comment by adriens** [comment]
Looks pretty good for a first version :-D

**Comment by adriens** [comment]
more infos about oh my zsh ! 
https://github.com/robbyrussell/oh-my-zsh

**Comment by sualeh** [comment]
Cool!

**Comment by sualeh** [comment]
[Adiren](@adriens), this pull request is for oh-my-zsh, not for SchemaCrawler, correct?

**Comment by adriens** [comment]
Yep, correct. Could you assign me this issue ?

**Comment by adriens** [comment]
PR not yet merged on ohmyzsh :cry:

**Comment by sualeh** [comment]
Sorry - not all open source projects are responsive. When the changes are merged, let me know, and I will make a note on the SchemaCrawler website.

**Comment by adriens** [comment]
Sure @sualeh , i completelmy understand, no worry about that.
