### ISSUE TITLE
LintDispatch > Build fails with no critical lint

### ISSUE THREAD

**Issue by mbarre** [sualeh/SchemaCrawler#45]
Hi Sualeh,

I think we've just found a bug with lintDispatch feature.

The build result is SUCCESS only if there is no lint detected. Even low lint makes the build to fail.

```
Summary of schema lints:
   [low]*     1- should have remarks

mars 21, 2016 11:23:49 AM schemacrawler.tools.lint.LintDispatch$4 dispatch
GRAVE: Too many schema lints were found
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.210 s
[INFO] Finished at: 2016-03-21T11:23:49+11:00
[INFO] Final Memory: 9M/150M
[INFO] ------------------------------------------------------------------------

```

I created a test case for you.
Here the maven project to exec the build, with our config file and sql script for database creation :
[test_dispatch.zip](https://github.com/sualeh/SchemaCrawler/files/181577/test_dispatch.zip)

Let me know if I did something wrong or if it's really a bug.
Thanks.

**Comment by sualeh** [comment]
This sounds like a bug. I will take a look.
