### ISSUE TITLE
[Question] Is it possible to exclude drawing one relationship?

### ISSUE THREAD

**Issue by dewind** [sualeh/SchemaCrawler#5]
I am generating a database diagram and there is one table that is referenced by almost every other table (Created and edited by ids) and pollutes the diagram to such a degree that I'd rather exclude it and just manually notate it.

The only thing I was able to do in order to work around it was exclude the column, which isn't ideal.

**Comment by sualeh** [comment]
Are you using the commandline? Try something like
```
-tables=.*\.(?!MYTABLENAME).*
```

**Comment by dewind** [comment]
Yes, I am using the command line.

That will keep the tables in-tact but exclude the relationship to the other tables?

**Comment by sualeh** [comment]
That will exclude your table completely from the diagram. Try it out, and let me know if it works for you.

**Comment by sualeh** [comment]
No reply, so closing issue.

**Comment by karlic** [comment]
When trying to exclude a table on the command line

`--tables=.*\.(?!MYTABLENAME).*`

didn't work for me, but this did:

`--tables='^((?!MYTABLENAME).)*$'`

(Note TWO minus signs were needed before` tables=`)
