### ISSUE TITLE
LintDispatch > Build always succeed

### ISSUE THREAD

**Issue by mbarre** [sualeh/SchemaCrawler#52]
Hi Sualeh,

I've just updated to v14.07.07.
I seems that critical lint hits are not detected any more, and the build never fails.

I join my test project, where I set LinterTableWithNoPrimaryKey to critical and create a table without primary key.

Let me know if I missed something.

Thanks.

**Comment by mbarre** [comment]
Sorry, I didn't join the right project.
Here is the good one.
[test_dispatch_wopk.zip](https://github.com/sualeh/SchemaCrawler/files/207749/test_dispatch_wopk.zip)

**Comment by sualeh** [comment]
Instead of `<dispatch-threshold>`, please use `<threshold>` and let me know. Thanks.

**Comment by mbarre** [comment]
Arrrgh.... Sorry, it's ok with <threshold>. I didn't see my mistake.
Thanks for your help.
