### ISSUE TITLE
How to add additional command line paramater to lints

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#54]
Hi @sualeh , i have a new lint idea. But for this new lint, i need to be able to pass additional parameters in the lint command line : any idea/example on how to do that please ?

**Comment by adriens** [comment]
See https://github.com/mbarre/schemacrawler-additionnallints/issues/60 for more details

**Comment by sualeh** [comment]
With SchemaCrawler 14.08.06, command-line parameters as well as parameters from the SchemaCrawler configuration file are available to individual linters. You can access these from the linter's `config` method.

**Comment by adriens** [comment]
Great, thanks for update @sualeh 
:+1:

**Comment by sualeh** [comment]
@adriens Please use the new release, and let me know.
