### ISSUE TITLE
Lints > How to exclude a column from a lint with config file

### ISSUE THREAD

**Issue by mbarre** [sualeh/SchemaCrawler#57]
Hi @sualeh , 

How are you doing ?

I have a question about lint config file and column exclusion.

I try to exclude the column "version" (hibernate reserved column) from **schemacrawler.tools.linter.LinterTableWithQuotedNames** lint. But I didn't manage to do it, I tried many regex that seem to be good. 

Here some examples, of what I tried

1_ exclude schemaname.tablename."columnname"
```
<linter id="schemacrawler.tools.linter.LinterTableWithQuotedNames">
<run>true</run>
<column-exclusion-pattern><![CDATA[(\w*.){2}"version"]]></column-exclusion-pattern>
</linter>
```

2_ exclude tablename."columnname"
```
<linter id="schemacrawler.tools.linter.LinterTableWithQuotedNames">
<run>true</run>
<column-exclusion-pattern><![CDATA[\w*."version"]]></column-exclusion-pattern>
</linter>
```

3_ exclude "columnname"
```
<linter id="schemacrawler.tools.linter.LinterTableWithQuotedNames">
<run>true</run>
<column-exclusion-pattern><![CDATA["version"]]></column-exclusion-pattern>
</linter>
```
But nothing is working...
So, I would like to know if <column-exclusion-pattern> is still used in config file ? Or is there another way to exclude column ?

**Comment by mbarre** [comment]
I've just tested it. :+1: 
Thanks

**Comment by sualeh** [comment]
Thanks for checking.

**Comment by adriens** [comment]
Great news !
