### ISSUE TITLE
native lint report improvement

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#59]
It would be cool to be able to inject formatted (bold, italic, color) html content in lint descriptions/comment in the native lint report.

**Comment by sualeh** [comment]
Any sample report idea?

**Comment by adriens** [comment]
For now, just put bold text to emphasis values in lint details

**Comment by adriens** [comment]
It's just a dummy question. We really want to focus on creating custome thymeleaf template report for lints ;-p

**Comment by sualeh** [comment]
Closed for now
