### ISSUE TITLE
Modify schemacrawler command line help

### ISSUE THREAD

**Issue by pyrocks** [sualeh/SchemaCrawler#62]
Following our discussion in the forum ([https://sourceforge.net/p/schemacrawler/discussion/495990/thread/784fd8a3/]) - here are a few suggestions:

1. help for -command=graph should display relevant outputformat for graphviz, not the standard outputformat. if you want you can redirect to the output format webpage of graphviz
2. when displaying help for a specific sub-section, in example a specific command - it should only display the help relevant to that command/sub-section and not the entire help all over again (help should be more focused on help needed by user's input).

**Comment by sualeh** [comment]
Thanks, Mor. I will fix this.
