### ISSUE TITLE
Enhancement Request: Embed input filters into queries

### ISSUE THREAD

**Issue by pyrocks** [sualeh/SchemaCrawler#63]
Hi,
following our [discussion](https://sourceforge.net/p/schemacrawler/discussion/495990/thread/7807396c) - please embed the input filters into the queries such that they will run faster, in example schemas=... should be added as and regexp_like(username,<input_regexp_expression>).

Thanks,
Mor

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.08.01

**Comment by pyrocks** [comment]
Hi,
Thanks for the update. I'll be OOO for the next 2-3 weeks so it might take me some time to check.
Will update.
Mor
