### ISSUE TITLE
14.08.04 release is lacking the zip distribution

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#73]

**Comment by sualeh** [comment]
I checked on a browser that I was not logged into, and I can see the release. Please check again.
https://github.com/sualeh/SchemaCrawler/releases

**Comment by adriens** [comment]
Hi @sualeh , just made the test, only source code is available, see screenshot below :

![lacking](https://cloud.githubusercontent.com/assets/5235127/15594034/7d95960c-23fd-11e6-912a-6613e00fe746.png)

**Comment by adriens** [comment]
![lacking](https://cloud.githubusercontent.com/assets/5235127/15594061/d49b8588-23fd-11e6-8a2b-fc2648532204.png)

**Comment by sualeh** [comment]
Thanks, [Adrien](@adriens). Seems like Travis screwed up. I will republish.

**Comment by sualeh** [comment]
Fixed now. Thanks for pointing it out!

**Comment by adriens** [comment]
:+1:
