### ISSUE TITLE
Column-exclusion in config file is ignored in LinterTableWithIncrementingColumns

### ISSUE THREAD

**Issue by mbarre** [sualeh/SchemaCrawler#75]

**Comment by mbarre** [comment]
Hi Sualeh,

I fixed it in my PR. I used getColumns(table) instead of table.getColumns().

Unless this is the way you want linters to work, I think you have the same issue in the following linters :
- LinterNullIntendedColumns
- LinterTableWithBadlyNamedColumns
- LinterTableWithNoRemarks
- LinterTableWithPrimaryKeyNotFirst

Let me know :)

**Comment by sualeh** [comment]
Thanks. I will fix all of these linters.

**Comment by mbarre** [comment]
:+1:

**Comment by mbarre** [comment]
I tested it this morning, it works thanks !

**Comment by sualeh** [comment]
:+1:
