### ISSUE TITLE
PDF generated is blank on a schema with many objects

### ISSUE THREAD

**Issue by pyrocks** [sualeh/SchemaCrawler#81]
Hi,

It looks more like a bug in dot than in schemacrawler - but maybe you know:
If I try to generate a PDF using -graph -outputformat=pdf on a schema with many tables, when I open the generated PDF it appears as blank. It's not actually blank since if I select a portion of it it highlights some blank table cells with no text in them, as if the tables are there but with no text.
![graphviz_generating_blank_like_pdf](https://cloud.githubusercontent.com/assets/18515297/16841145/898633dc-49e0-11e6-9d1d-4ba4b99c1234.jpg)

I tried running dot manually on the generated dot file (took it's location from the log) and it appears to have 1000+ nodes.

Any other format I tried works - in example JPG - the entire ERD is shown, but the file is much much larger (9M vs 220k as PDF).

On smaller schemas the generated pdf is fine.

This looks similar to this:
[graphviz bug](http://www.graphviz.org/mantisbt/view.php?id=2542)
or this
[another graphviz bug](http://www.graphviz.org/mantisbt/view.php?id=1309)
but I tried to run dot in verbose (-v) and did not see a warning.

Have any idea?

Thanks.

**Comment by pyrocks** [comment]
I went through the [dot guide](http://www.graphviz.org/pdf/dotguide.pdf) especially section 2.5 "Drawing Orientation, Size and Spacing" and managed to get the PDF working by adding size="7.5,10" to the first [graph] properties, above nodesep="0.18"

While i'm not sure this is the best setting for all scenarios - would it be possible to somehow configure it from SchemaCrawler's config or command line?

You are more than welcome doing more tests on the "size" and "ratio" properties.

Let me know what you think.
Mor

**Comment by sualeh** [comment]
Mor,

1. This is an Adobe Acrobat Reader issue. Foxit Reader opens the big files just fine.
2. Please read the [SchemaCrawler documentation on how to set GraphViz properties](http://sualeh.github.io/SchemaCrawler/diagramming.html).

Sualeh.
