### ISSUE TITLE
Enhancement: to be able to hide schema names but not constraint names

### ISSUE THREAD

**Issue by pyrocks** [sualeh/SchemaCrawler#83]
Hi,

I would like to request the option to hide schema names when generating an html output with command=schema (/brief/details).
currently -portablenames=true hides both the schema names and all constraint names - but I want the constraint names to appear.

one option is to add more options to the -portablenames option, in example=true/false/schemas only/constraints only etc.

Thanks,
Mor

**Comment by sualeh** [comment]
http://sualeh.github.io/SchemaCrawler/how-to.html#hide-schema-names

**Comment by pyrocks** [comment]
2 comments:
1. It would be nice to have the option directly from the command line without a config file (I don't like having extra files to manage).
2. the documentation is too scattered in the site (to me at least).

**Comment by sualeh** [comment]
1. I hesitate to add more options to the command-line. The options are complicated enough with the use cases that most users want. What I can offer you is a SchemaCrawler config properties file that you keep in the SchemaCrawler `lib/` folder, that acts as defaults. Will that work?
2. I will see what I can do about the documentation. That being said, use Google to find SchemaCrawler documentation. If you had searched for "schemacrawler hide schemas" on Google, the first result would told you how.

**Comment by pyrocks** [comment]
1.no need, i will use a local config file (it works well)
2. Will keep in mind the google option.
Thanks for the help.

**Comment by pyrocks** [comment]
Hi,
1 more Q - what sets the color of the table name background in the generated HTML?
Every time I generate a file I get a different color - is it random or calculated on something?
If it's random (I assume it's not) - might be problematic when doing a diff.
I did try to google "schemacrawler color" but found nothing useful.

**Comment by sualeh** [comment]
The color is generated based on the schema name. It will be the same for a given schema. It will be an enhancement to allow setting specified colors for a schema.

**Comment by pyrocks** [comment]
why not use the same color for all html output?

**Comment by sualeh** [comment]
Well, you can have multiple schemas in a single diagram, and also many diagrams on subsets of your schema. This way, you are guaranteed the same color for a given schema name. Anyway, if you want to specify colors, please enter in an enhancement request.
