### ISSUE TITLE
Enhancement: To be able to specify report color/disable coloring by name

### ISSUE THREAD

**Issue by pyrocks** [sualeh/SchemaCrawler#84]
Hi,

The reason I want this is because our schema are named [base_name]_[version]

In example SCHEMA1_0100 and SCHEMA1_0200
I want to be able to compare between them since it's the same schema - just different versions of it - without the color specifications coming up on the diff.

Either way - to be able to specify report color/disable coloring by name - is good for my purposes.

Thanks again,
Mor

**Comment by sualeh** [comment]
Please use SchemaCrawler 14.09.03. You will need to set a new configuration value in your properties file, `schemacrawler.format.no_schema_colors=true`

**Comment by pyrocks** [comment]
Thanks a lot, I will test it later today.

**Comment by pyrocks** [comment]
New configuration value is working correctly, :+1: .

**Comment by sualeh** [comment]
Excellent.

**Comment by pyrocks** [comment]
Hi,
Another question - when comparing 2 HTMLS I get different "span id" values for the same object (table). Any way to avoid that?
Thanks

**Comment by sualeh** [comment]
Mor, you cannot avoid different span id values. SchemaCrawler needs to ensure that the id is unique, and it does that by deriving the id based off the fully qualified database object name. What you can do, though, is to generate output in text format, and compare that.

**Comment by pyrocks** [comment]
I thought about that - then I might have to generate 2 type of files (1 for readability and another for compare). will check that. Thanks.

**Comment by sualeh** [comment]
That may be a good idea. The HTML compare can get messy if you do not have a good compare tool. If you do use a good HTML compare tool, it should be able to filter out mismatches between ids.
