### ISSUE TITLE
To be able to specify color by schmea 

### ISSUE THREAD

**Issue by mannysangra** [sualeh/SchemaCrawler#86]
Hi,

How can I specify different colour for each schema ? 
The reason I want this is because our tables are named  [schmea_name.table_name]

In example : 
SCHEMA1 has got 2 table (ex: schema_name.table_name1,schema_name.table_name2)
SCHEMA 2 has got 2 table 
SCHEMA 3 has got 4 table 
When I have generate SchemaCrawler, for some reason the tables of SCHEMA 2 and SCHMEA 3 has got same color for tables..

Thanks again,
Maninder Singh

**Comment by sualeh** [comment]
You can create a file called `schemacrawler.colormap.properties` in the `lib/` folder or the current working directory, and specify custom color mappings.

The syntax is an HTML color preceded by a dash, and a regular expression.
```
-#FF9999=<regular expression for schema>
```
