### ISSUE TITLE
use "$@" instead of $*

### ISSUE THREAD

**Issue by elyashiv** [sualeh/SchemaCrawler#87]
In the .sh scripts you use $\* witch expands to the parameters given to the script. According to [the bash manual](https://www.gnu.org/software/bash/manual/html_node/Special-Parameters.html) the use of "$@" will expand to the same thing, just quoted, something that can be quite useful.

**Comment by sualeh** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;1xNt0wWt&#x2F;239-use-shell-wildcard"><img src="https:&#x2F;&#x2F;github.trello.services&#x2F;images&#x2F;trello-icon.png" width="12" height="12"> Use shell wildcard</a>
