### ISSUE TITLE
Parameters in database connection url are ignored

### ISSUE THREAD

**Issue by Spamme1** [sualeh/SchemaCrawler#91]
I'm trying to connect to sql server 2014 with integrated security and I use the database connection url as specified [here](http://sualeh.github.io/SchemaCrawler/database-support.html). But I doesn't work because without a user name and password schemacrawler asks for a "password". Why? I want to log in with the actual user credentials ... is it possible?
```
schemacrawler.cmd -c graph -server=sqlserver -url=jdbc:jtds:sqlserver://localhost:1433/[DbName]?useuseNTLMv2=true -schemas=dbo  -infolevel=detailed -outputformat=pdf -outputfile=database-diagram.pdf 

SchemaCrawler 14.10.01
Database schema discovery and comprehension tool
Copyright (c) 2000-2016, Sualeh Fatehi <sualeh@hotmail.com>.

You can search for database schema objects using regular expressions,
and output the schema and data in a readable text format. You can find
potential schema design issues with lint. The output serves for
database documentation is designed to be diff-ed against other database
schemas. SchemaCrawler also generates schema diagrams.
password:
```

So I tried to add the user name and password to the database connection url, as specified in the [documentation](http://jtds.sourceforge.net/faq.html), but it doesn't work neither, schemacrawler asks again for a "password":
```
schemacrawler.cmd -c graph -server=sqlserver -url=jdbc:jtds:sqlserver://localhost:1433/[DbName]?useuseNTLMv2=true;user=vagrant;password=vagrant -schemas=dbo  -infolevel=detailed -outputformat=pdf -outputfile=database-diagram.pdf`
```

The only way to specify a user name and password is to add them to the arguments of schemacrawler, but it doesn't work neither:
```
schemacrawler.cmd -c graph -server=sqlserver -url=jdbc:jtds:sqlserver://localhost:1433/[DbName]?useuseNTLMv2=true; -user=vagrant -password=vagrant -schemas=dbo  -infolevel=detailed -outputformat=pdf -outputfile=database-diagram.pdf

SchemaCrawler 14.10.01

Error: Could not connect to jdbc:jtds:sqlserver://localhost:1433/[DbName]?useuseNTLMv2=true;, for user 'vagrant', with properties {}
```

**Comment by Spamme1** [comment]
After googling for hours I finding pieces of information on different pages I could put together something that is working:
```
schemacrawler.cmd -c details -server=sqlserver -url="jdbc:jtds:sqlserver://localhost;integratedSecurity=true;" -schemas=[DBName].dbo -user= -password= -infolevel=detailed -outputformat=html -outputfile=database-diagram.html
```
To use integrated security you have also to download the [jtds project](https://github.com/milesibastos/jTDS) and copy the ntlmauth.dll in a reachable path ([readme.sso](https://github.com/milesibastos/jTDS/blob/master/README.SSO))

**Comment by sualeh** [comment]
Thanks for doing this research. This will help other users. I will update the documentation on [the SchemaCrawler database support page](http://sualeh.github.io/SchemaCrawler/database-support.html).
