### ISSUE TITLE
How to create a HTML5 with embedded diagrams?

### ISSUE THREAD

**Issue by Spamme1** [sualeh/SchemaCrawler#92]
I can't find anywhere how to output "html5 with embedded diagrams" as mentioned [here](http://sualeh.github.io/SchemaCrawler/output.html), which should give this [result](http://sualeh.github.io/SchemaCrawler/snapshot-examples/snapshot.svg.html).
It is not clear which command should be used: graph, details, schema, brief? Because the graph is the only one producing a diagram, but the output is a picture, all the other commands can produce html as output but without diagrams. 
The lack of documentation and examples is really frustrating!

**Comment by sualeh** [comment]
Please use -outputformat=htmlx. Also, please note that documentation is available with -help on the command-line.

**Comment by Spamme1** [comment]
Sorry but I don't see anywhere the htmlx option in the help, which command should have it?

```
-outputformat=<outputformat>
  Format of the SchemaCrawler output, where <outputformat> is one of:
    text
      For text output (default)
    html
      For HTML5 output
    csv
      For comma-separated values output
    tsv
      For tab-separated values output
    json
      For JavaScript Object Notation output
  Optional, defaults to text
```
```
-outputformat=<outputformat>
        Where <outputformat> is one of bmp, dot, eps, gif, jpg, png, ps2, tiff.
        If Graphviz is not installed, a dot file is produced.
```

**Comment by sualeh** [comment]
I am not at my computer, but please try it out. I will look into the documentation later.

**Comment by Spamme1** [comment]
I tried with the command "details" and it works, but this "htmlx" option is not documented anywhere.

**Comment by sualeh** [comment]
Ok, thanks. I will add documentation.
