### ISSUE TITLE
Comments on tables in PostgreSQL missing

### ISSUE THREAD

**Issue by domosapien** [sualeh/SchemaCrawler#94]
Specifically in the graphviz output (haven't checked others), the comments are missing at the table level (column level comments are present).

**Comment by sualeh** [comment]
[Zach](@domosapien), I checked that tables comments do show up in graphs. We will need to debug your specific case. Please me debugging logs by email, after running SchemaCrawler with `-loglevel=ALL`. Thanks.

**Comment by domosapien** [comment]
Sorry for opening the issue and wasting your time, it is definitely a problem with the schema definition (comment was being applied to the wrong table). I should have reviewed the problem more closely. Verified it works as expected once the schema was fixed.

**Comment by sualeh** [comment]
No worries. Unfortunately, SchemaCrawler does not automatically write comments for you yet. Maybe in a future version.
