### ISSUE TITLE
Create ditaa text file with db diagram

### ISSUE THREAD

**Issue by ptahchiev** [sualeh/SchemaCrawler#96]
I would like to see a way to generate a ditaa diagram:

http://ditaa.sourceforge.net/

for my database schema instead of an image with graphviz. If you could create a text file which then I can use ditaa to create an image that would be really awesome.

**Comment by sualeh** [comment]
SchemaCrawler has all the capabilities to allow you to do this. Please use SchemaCrawler's templating feature with either Apache Velocity or Freemarker to generate these files.

**Comment by adriens** [comment]
Looks like an interesting idea, let us know when you achieved something that you can show ;-p
