### ISSUE TITLE
Website looking strange on github

### ISSUE THREAD

**Issue by adriens** [sualeh/SchemaCrawler#97]
![obsn5](https://cloud.githubusercontent.com/assets/5235127/20412027/5b1e751c-ad78-11e6-94a3-b1e8614f72e3.png)

**Comment by sualeh** [comment]
Adrien, that can happen if the browser has not loaded all of the CSS and JavaScript. What browser are you using, and what operating system? The site loads fine for me.

**Comment by adriens** [comment]
FF from

```
Linux Mint 17.3 Rosa \n \l
```

It does now look good.
